baseURL = 'https://garrettsiegel.com/'
languageCode = 'en-us'
enableRobotsTXT = true

[security.exec]
  allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$', '^babel$']
  osEnv = ['(?i)^((HTTPS?|NO)_PROXY|PATH(EXT)?|APPDATA|TE?MP|TERM)$']